<?php
echo '<tr><td>Cutomer ID</td>';
echo '<td>';
echo $row['cus_id']  ;
echo '</td>';
echo "</tr>";
echo '<tr><td>Cutomer Name</td>';
echo '<td>';
echo $row['cus_name']  ;
echo '</td>';
echo "</tr>";
echo '<tr><td>Cutomer NIC</td>';
echo '<td>';
echo $row['cus_nic']  ;
echo '</td>';
echo "</tr>";
echo '<tr><td>Address 1</td>';
echo '<td>';
echo $row['add1']  ;
echo '</td>';
echo "</tr>";
echo '<tr><td>Address 2</td>';
echo '<td>';
echo $row['add2']  ;
echo '</td>';
echo "</tr>";
echo '<tr><td>Address 3</td>';
echo '<td>';
echo $row['add3']  ;
echo '</td>';
echo "</tr>";
echo '<tr><td>Customer E-mail</td>';
echo '<td>';
echo $row['cus_email']  ;
echo '</td>';
echo "</tr>";
echo '<tr><td>Customer Contact No</td>';
echo '<td>';
echo $row['cus_contact']  ;
echo '</td>';
echo "</tr>";
?>